### ISSUE TITLE
configuration_name@interface functionality

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/multus-cni#4]
As commented in the spec:

> To follow up, Per/Suresh suggested decorating the CNI network name in a "standardized" way that the meta-plugin/runtime would recognize, eg the plugin would see a JSON "name" field of "networkA@eth0" and "networkA@eth1" for two different attachment requests. It seems like this could work.

Perhaps we should suggest that when using the comma-delimited style it looks like:

```
kubernetes.cni.cncf.io/v1/networks:  netA@eth0,netB@eth1
```

And then add a field in the JSON style, such as:

```json
[{
		"name": "netA"
	},
	{
		"name": "netB",
		"interfaceRequest": "eth5",
		"ipRequest": "1.2.3.4",
		"macRequest": "aa:bb:cc:dd:ee:ff"
	},
	{
		"name": "other-ns/NetC"
	}
]
```

Also of note, Multus currently will use `eth0` for the first interface, and then use `net0` for the next interface, and then `net1`, `net2`, ..., `netN` etc. It does so with the [getifname](https://github.com/Intel-Corp/multus-cni/blob/dev/network-plumbing-working-group-crd-change/multus/multus.go#L134) method.

**Comment by s1061123** [comment]
Currently  I also agree with Suresh proposal, however I just remembered that currently linux uses '@' for ifname convention. For example, linux `ip` command (of iproute2) shows veth like "<ifname>@<peer if of veth>".  So we may see '<netconf name>@<ifname>@<peer if of veth>' as following (I did in my server).

It may be confused so we may provide another character in prototype (and discussion).

```
tom@kagaribi $ ip a
(snip)
35: veth9a3dd1b@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1454 qdisc noqueue master docker0 state UP group default 
    link/ether 46:1e:10:e0:88:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::441e:10ff:fee0:88e9/64 scope link 
       valid_lft forever preferred_lft forever
tom@kagaribi $ sudo ip link set dev veth9a3dd1b name test@eth0
RTNETLINK answers: Device or resource busy
tom@kagaribi $ sudo ip link set dev veth9a3dd1b down          
tom@kagaribi $ sudo ip link set dev veth9a3dd1b name test@eth0
tom@kagaribi $ sudo ip link set dev test@eth0 up
tom@kagaribi $ ip a
(snip)
35: test@eth0@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1454 qdisc noqueue master docker0 state UP group default 
    link/ether 46:1e:10:e0:88:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::441e:10ff:fee0:88e9/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by s1061123** [comment]
working on dev/add_if_name branch.
